export const locations = [
  { value: "Hà Nội", label: "Hà Nội" },
  { value: "Hải Phòng", label: "Hải Phòng" },
  { value: "Huế", label: "Huế" },
  { value: "Đà Nẵng", label: "Đà Nẵng" },
  { value: "TP. Hồ Chí Minh", label: "TP. Hồ Chí Minh" },
  { value: "Cần Thơ", label: "Cần Thơ" },

  { value: "Tuyên Quang", label: "Tuyên Quang" },
  { value: "Cao Bằng", label: "Cao Bằng" },
  { value: "Lạng Sơn", label: "Lạng Sơn" },
  { value: "Lai Châu", label: "Lai Châu" },
  { value: "Điện Biên", label: "Điện Biên" },
  { value: "Sơn La", label: "Sơn La" },
  { value: "Lào Cai", label: "Lào Cai" },
  { value: "Thái Nguyên", label: "Thái Nguyên" },
  { value: "Phú Thọ", label: "Phú Thọ" },
  { value: "Quảng Ninh", label: "Quảng Ninh" },
  { value: "Bắc Ninh", label: "Bắc Ninh" },
  { value: "Hưng Yên", label: "Hưng Yên" },
  { value: "Ninh Bình", label: "Ninh Bình" },
  { value: "Thanh Hóa", label: "Thanh Hóa" },
  { value: "Nghệ An", label: "Nghệ An" },
  { value: "Hà Tĩnh", label: "Hà Tĩnh" },
  { value: "Quảng Trị", label: "Quảng Trị" },
  { value: "Quảng Ngãi", label: "Quảng Ngãi" },
  { value: "Gia Lai", label: "Gia Lai" },
  { value: "Khánh Hòa", label: "Khánh Hòa" },
  { value: "Lâm Đồng", label: "Lâm Đồng" },
  { value: "Đắk Lắk", label: "Đắk Lắk" },
  { value: "Đồng Nai", label: "Đồng Nai" },
  { value: "Tây Ninh", label: "Tây Ninh" },
  { value: "Vĩnh Long", label: "Vĩnh Long" },
  { value: "Đồng Tháp", label: "Đồng Tháp" },
  { value: "Cà Mau", label: "Cà Mau" },
  { value: "An Giang", label: "An Giang" },
];